name: gallery_dev
channels:
  - openalea3/label/rc
  - openalea3/label/dev
  - conda-forge
dependencies:
  - python >=3.13
  - openalea.plantgl
  - openalea.lpy
  - openalea.caribu
  - openalea.hydroroot
  - openalea.phenomenal
  - openalea.oalab
  - oawidgets
  - openalea.mtg
  - jupyterlab
  - nodejs
  - pip
  - pip:
      - jupyter-book==2.*
      - --pre