name: gallery_dev
channels:
  - openalea3/label/dev
  - openalea3/label/rc
  - openalea3
  - conda-forge
dependencies:
# some of the pkgs install dependencies like lpy and visualea
  - python >=3.13
  - openalea.lpy
  - openalea.widgets
  - openalea.hydroroot
  - openalea.astk
  - openalea.caribu
  - openalea.visualea
  - openalea.phenomenal
  - openalea.adel
  - openalea.wheatfspm
  - openalea.ratp
  - jupyterlab
  - nodejs
  - pip
  - pip:
      - jupyter-book==2.*
      - --pre
