pre: git clone https://github.com/openalea/gallery gallery

packages:
    - name      : openalea.weberpenn
      vcs       : conda
      cmd       : mamba install -y
      hierarchy : patch
      supply    : minor
      channels:
        - openalea3/label/rc
        - openalea3
        - conda-forge

    - name      : openalea.visualea
      vcs       : conda
      cmd       : mamba install -y
      hierarchy : patch
      supply    : minor
      channels:
        - openalea3/label/rc
        - openalea3
        - conda-forge

    - name      : openalea.grapheditor
      vcs       : conda
      cmd       : mamba install -y
      hierarchy : patch
      supply    : minor
      channels:
        - openalea3/label/rc
        - openalea3
        - conda-forge

    - name      : openalea.core
      vcs       : conda
      cmd       : mamba install -y
      hierarchy : patch
      supply    : minor
      channels:
        - openalea3/label/rc
        - openalea3
        - conda-forge

    - name      : openalea.oalab
      vcs       : conda
      cmd       : mamba install -y
      hierarchy : patch
      supply    : minor
      channels:
        - openalea3/label/rc
        - openalea3
        - conda-forge
    - name      : openalea.caribu
      vcs       : conda
      cmd       : mamba install -y
      hierarchy : patch
      supply    : minor
      channels:
        - openalea3/label/rc
        - openalea3
        - conda-forge
    - name      : openalea.libcaribu
      vcs       : conda
      cmd       : mamba install -y
      hierarchy : patch
      supply    : minor
      channels:
        - openalea3/label/rc
        - openalea3
        - conda-forge
    - name      : openalea.mtg
      vcs       : conda
      cmd       : mamba install -y
      hierarchy : patch
      supply    : minor
      channels:
        - openalea3/label/rc
        - openalea3
        - conda-forge
    - name      : openalea.lpy
      vcs       : conda
      cmd       : mamba install -y
      hierarchy : patch
      supply    : minor
      channels:
        - openalea3/label/rc
        - openalea3
        - conda-forge

    - name      : openalea.plantgl
      vcs       : conda
      cmd       : mamba install -y
      hierarchy : patch
      supply    : minor
      channels:
        - openalea3/label/rc
        - openalea3
        - conda-forge

    - name      : openalea.astk
      vcs       : conda
      cmd       : mamba install -y
      hierarchy : patch
      supply    : minor
      channels:
        - openalea3/label/rc
        - openalea3
        - conda-forge

    - name      : openalea.widgets
      vcs       : conda
      cmd       : mamba install -y
      hierarchy : patch
      supply    : minor
      channels:
        - openalea3/label/rc
        - openalea3
        - conda-forge

    - name      : matplotlib-base
      vcs       : conda
      cmd       : mamba install -y
      hierarchy : patch
      supply    : minor

    - name      : python
      vcs       : conda
      cmd       : mamba install -y
      hierarchy : patch
      supply    : major


run:
    - python -c 'import openalea.plantgl'

post: mamba env export > environment.yml
